## 파이썬
# 파이썬 기초

### 파일 입출력

In [1]:
f = open('안녕.txt', encoding='cp949') # 'utf-8' (윈도우에서 기본은 'cp949')
s = f.read() # 텍스트 파일의 모든 내용을 읽어온다
f.close() # 파일 사용이 끝나면 항상 닫아준다

print(s)

안녕하세요
반가워요~


In [3]:
f = open('안녕.txt')
for line in f: # 라인 단위로 처리한다 (개행문자가 포함됨)
    print(line.strip())
f.close()

안녕하세요
반가워요~


In [5]:
f = open('안녕.txt')
s1 = f.readline()
s2 = f.readline()
f.close()

print(s1)
print(s2)

안녕하세요

반가워요~


In [6]:
f = open('안녕.txt') # encoding='cp949'
s = f.readline() # 헤더 부분을 먼저 읽어온다
print(s)

for line in f:
    print(line.strip())

f.close()

안녕하세요

반가워요~


### 연습문제

```
이름,나이,지역
홍길동,22,서울
장길산,33,춘천
둘리,5,우주
```
- 위의 데이터를 '인물.txt' 로 저장하고, 2차원 리스트로 불러와 보자
- strip(), split() 함수 사용
- encoding='cp949' 또는 encoding='utf-8'

In [11]:
f = open('인물.txt', encoding='utf-8')
s = f.readline()
print(s)

data = []

for line in f:
    l = line.strip().split(',') # 리스트로 변환
    l[1] = int(l[1]) # 정수로 바꿔준다
    data.append(l)

f.close()

print(data)

이름,나이,지역

[['홍길동', 22, '서울'], ['장길산', 33, '춘천'], ['둘리', 5, '우주']]


### 연습문제

```
이름,나이,지역
홍길동,22,서울
장길산,33,춘천
둘리,5,우주
```
- '인물2.txt' 로 저장 후, 다시 불러오기

In [13]:
f = open('인물2.txt', 'w')
f.write('이름,나이,지역\n')
f.write('홍길동,22,서울\n')
f.write('장길산,33,춘천\n')
f.write('둘리,5,우주\n')
f.close()

In [15]:
f = open('인물2.txt')
s = f.readline()
print(s)

data = []

for line in f:
    l = line.strip().split(',') # 리스트로 변환
    l[1] = int(l[1]) # 정수로 바꿔준다
    data.append(l)

f.close()

print(data)

이름,나이,지역

[['홍길동', 22, '서울'], ['장길산', 33, '춘천'], ['둘리', 5, '우주']]


In [17]:
with open('인물2.txt') as f:
    s = f.readline()
    print(s)

    data = []

    for line in f:
        l = line.strip().split(',') # 리스트로 변환
        l[1] = int(l[1]) # 정수로 바꿔준다
        data.append(l)

print(data)

이름,나이,지역

[['홍길동', 22, '서울'], ['장길산', 33, '춘천'], ['둘리', 5, '우주']]


### 파일과 디렉토리 관리

In [18]:
import math # 라이브러리, 모듈

In [20]:
math.sin(2)

0.9092974268256817

In [21]:
math.sqrt(25)

5.0

In [22]:
import os # sys, io

In [23]:
os.getcwd() # get current working directory

'D:\\python'

In [24]:
os.chdir('..') # 앞 디렉토리로 이동
os.getcwd()

'D:\\'

In [28]:
os.chdir('c:\\Temp') # 절대경로 지정 (\\ 사용, / 도 가능함)
os.getcwd()

'c:\\Temp'

In [29]:
os.chdir('d:\\python')
os.getcwd()

'd:\\python'

In [27]:
dir(os) # import 를 먼저 실행해야 한다

['DirEntry',
 'F_OK',
 'MutableMapping',
 'O_APPEND',
 'O_BINARY',
 'O_CREAT',
 'O_EXCL',
 'O_NOINHERIT',
 'O_RANDOM',
 'O_RDONLY',
 'O_RDWR',
 'O_SEQUENTIAL',
 'O_SHORT_LIVED',
 'O_TEMPORARY',
 'O_TEXT',
 'O_TRUNC',
 'O_WRONLY',
 'P_DETACH',
 'P_NOWAIT',
 'P_NOWAITO',
 'P_OVERLAY',
 'P_WAIT',
 'PathLike',
 'R_OK',
 'SEEK_CUR',
 'SEEK_END',
 'SEEK_SET',
 'TMP_MAX',
 'W_OK',
 'X_OK',
 '_Environ',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_execvpe',
 '_exists',
 '_exit',
 '_fspath',
 '_get_exports_list',
 '_putenv',
 '_unsetenv',
 '_wrap_close',
 'abc',
 'abort',
 'access',
 'altsep',
 'chdir',
 'chmod',
 'close',
 'closerange',
 'cpu_count',
 'curdir',
 'defpath',
 'device_encoding',
 'devnull',
 'dup',
 'dup2',
 'environ',
 'errno',
 'error',
 'execl',
 'execle',
 'execlp',
 'execlpe',
 'execv',
 'execve',
 'execvp',
 'execvpe',
 'extsep',
 'fdopen',
 'fsdecode',
 'fsencode',
 'fspath',
 'fstat',
 'fs

### iris 데이터 불러오기
- 2차원 리스트로 저장한다
- https://archive.ics.uci.edu/ml/datasets/Iris
- 숫자를 실수로 변환하자
- 마지막 칼럼은 품종이다. 이것을 0,1,2 와 같이 코드로 바꾸어 보자

In [30]:
s = ['one', 'two', 'one', 'three', 'two', 'three']
l = []

for i in s:
    l.append(1 if i=='one' else (2 if i=='two' else 3))
    
l

[1, 2, 1, 3, 2, 3]

In [32]:
f = open('iris.csv')

s = f.readline()
header = s.strip().split(',')

labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris = []

for line in f:
    l = line.strip().split(',')
    # 리스트의 index() 함수
    l = [float(l[0]), float(l[1]), float(l[2]), float(l[3]), labels.index(l[4])]
    '''
    l[0] = float(l[0])
    l[1] = float(l[1])
    l[2] = float(l[2])
    l[3] = float(l[3])
    l[4] = labels.index(l[4])
    '''
    iris.append(l)

f.close()

iris

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.4, 3.7, 1.5, 0.2, 0],
 [4.8, 3.4, 1.6, 0.2, 0],
 [4.8, 3.0, 1.4, 0.1, 0],
 [4.3, 3.0, 1.1, 0.1, 0],
 [5.8, 4.0, 1.2, 0.2, 0],
 [5.7, 4.4, 1.5, 0.4, 0],
 [5.4, 3.9, 1.3, 0.4, 0],
 [5.1, 3.5, 1.4, 0.3, 0],
 [5.7, 3.8, 1.7, 0.3, 0],
 [5.1, 3.8, 1.5, 0.3, 0],
 [5.4, 3.4, 1.7, 0.2, 0],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.6, 3.6, 1.0, 0.2, 0],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.0, 3.0, 1.6, 0.2, 0],
 [5.0, 3.4, 1.6, 0.4, 0],
 [5.2, 3.5, 1.5, 0.2, 0],
 [5.2, 3.4, 1.4, 0.2, 0],
 [4.7, 3.2, 1.6, 0.2, 0],
 [4.8, 3.1, 1.6, 0.2, 0],
 [5.4, 3.4, 1.5, 0.4, 0],
 [5.2, 4.1, 1.5, 0.1, 0],
 [5.5, 4.2, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.0, 3.2, 1.2, 0.2, 0],
 [5.5, 3.5, 1.3, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.4, 3.0, 

In [38]:
l = [1,2,3,4,5]
list(map(lambda x: x**2, l))

[1, 4, 9, 16, 25]

In [36]:
l = [-1,2,-3,4,-5]
list(map(abs, l))

[1, 2, 3, 4, 5]

In [37]:
f = open('iris.csv')

s = f.readline()
header = s.strip().split(',')

labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris = []

for line in f:
    l = line.strip().split(',')
    l[:4] = list(map(float, l[:4]))
    l[4] = labels.index(l[4])
    iris.append(l)

f.close()

iris

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.4, 3.7, 1.5, 0.2, 0],
 [4.8, 3.4, 1.6, 0.2, 0],
 [4.8, 3.0, 1.4, 0.1, 0],
 [4.3, 3.0, 1.1, 0.1, 0],
 [5.8, 4.0, 1.2, 0.2, 0],
 [5.7, 4.4, 1.5, 0.4, 0],
 [5.4, 3.9, 1.3, 0.4, 0],
 [5.1, 3.5, 1.4, 0.3, 0],
 [5.7, 3.8, 1.7, 0.3, 0],
 [5.1, 3.8, 1.5, 0.3, 0],
 [5.4, 3.4, 1.7, 0.2, 0],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.6, 3.6, 1.0, 0.2, 0],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.0, 3.0, 1.6, 0.2, 0],
 [5.0, 3.4, 1.6, 0.4, 0],
 [5.2, 3.5, 1.5, 0.2, 0],
 [5.2, 3.4, 1.4, 0.2, 0],
 [4.7, 3.2, 1.6, 0.2, 0],
 [4.8, 3.1, 1.6, 0.2, 0],
 [5.4, 3.4, 1.5, 0.4, 0],
 [5.2, 4.1, 1.5, 0.1, 0],
 [5.5, 4.2, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.0, 3.2, 1.2, 0.2, 0],
 [5.5, 3.5, 1.3, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.4, 3.0, 

In [40]:
len(iris), len(iris[0])

(150, 5)

### 클래스
- 클래스는 청사진을 만드는 것이다
- 클래스를 만들려면 설계를 잘해야 한다. 하지만 설계는 아주 어려운 일이다.
- 클래스가 현실화된 것이 **객체**(object)이다

In [46]:
class ABC:
    def first(self): # 함수 정의시 첫번째 인자는 반드시 self
        print('I am ABC')
        
    def secound(self, n):
        return n+1
        
abc = ABC() # 객체 생성
abc.first() # 함수를 호출할 때는 self 쓰지 않음
print(abc.secound(100))

I am ABC
101
The end...


In [60]:
class ABC:
    def __init__(self):
        self.name = 'ABC' # 변수 선언
        self.count = 3 # 변수 선언
        
    def first(self):
        print('I am', self.name)
        
    def secound(self, n):
        return n + self.count
    
    def third(self):
        pass
        #print('TEST: ')
        #self.first()
        
abc = ABC() # 객체 생성
abc.first() # 함수를 호출할 때는 self 쓰지 않음
print(abc.secound(100))
print(abc.name, abc.count)
print(abc.third())
print('kkk')

I am ABC
103
ABC 3
None
kkk


In [64]:
class ABC:
    def __init__(self, name): # 초기화함수에 인자가 있을 때
        self.name = name
        self.count = len(name)
        
    def first(self):
        print('I am', self.name)
        
    def secound(self, n):
        return n + self.count
    
    def third(self):
        print('TEST: ', end='')
        self.first()
        
abc = ABC("Hong Gil Dong") # 객체 생성
abc.first() # 함수를 호출할 때는 self 쓰지 않음
print(abc.secound(100))
print(abc.name, abc.count)
print(abc.third())

I am Hong Gil Dong
113
Hong Gil Dong 13
TEST: I am Hong Gil Dong
None


In [65]:
#class MyClass(OtherClass): # OtherClass 를 상속

### 모듈 (라이브러리)
- 모듈은 함수들을 묶은 것이다

In [66]:
import math

In [67]:
math.exp(10)

22026.465794806718

In [68]:
math.log(1)

0.0

In [69]:
from math import sin, cos

In [70]:
sin(0), cos(0) # math 를 붙이지 않는다

(0.0, 1.0)

In [71]:
import os as win # 이름 바꿔서 불러오기

In [72]:
win.getcwd()

'd:\\python'

- 나의 모듈 만들기
> 현재 디렉토리에 .py 파일을 만들고 import 로 불러온다

```
# my_source.py
X = ['a','b','c']

def my_first():
	print('First')
	
def my_secound(n):
	print(n+1)
```

In [78]:
import my_source as ms

In [79]:
ms.X

['a', 'b', 'c']

In [80]:
ms.my_first()

First


In [81]:
ms.my_secound(100)

101


### 예외처리

In [87]:
int('33')

33

In [88]:
int(33)

33

In [91]:
int(3.14)

3

In [90]:
int('3.14')

ValueError: invalid literal for int() with base 10: '3.14'

In [92]:
int('3abc')

ValueError: invalid literal for int() with base 10: '3abc'

In [97]:
s = '3.14'

try:
    n=int(s)
except:
    n=0
    
n

0

In [98]:
help(l.index) # ValueError 발생시킴

Help on built-in function index:

index(...) method of builtins.list instance
    L.index(value, [start, [stop]]) -> integer -- return first index of value.
    Raises ValueError if the value is not present.



In [102]:
l = [1,2,3,4,100]
n = 0

try:
    n = l.index(5)
except:
    n = 999
    
n

999

### Built-In Functions

In [103]:
help(all)

Help on built-in function all in module builtins:

all(iterable, /)
    Return True if bool(x) is True for all values x in the iterable.
    
    If the iterable is empty, return True.



In [106]:
all([0,1,2,3,4,-5])

False

In [108]:
any([0,0,0.00001,0,0])

True

In [116]:
isinstance(3.14, float)

True

In [120]:
이름 = ['홍길동','장길산','둘리','유관순','이순신']
수학 = [1,2,3,4,5]
영어 = [5,4,3,2,1]
국어 = [-1,-2,-3,-4,-5]

for i,j,k,l in zip(이름,수학,영어,국어):
    print(i,'=>',j,k,l)

홍길동 => 1 5 -1
장길산 => 2 4 -2
둘리 => 3 3 -3
유관순 => 4 2 -4
이순신 => 5 1 -5


In [122]:
l = [3,7,2,9,8]

n = 0
for i in l:
    print(n,'=>',i)
    n += 1

0 => 3
1 => 7
2 => 2
3 => 9
4 => 8


In [123]:
l = [3,7,2,9,8]

for i in range(len(l)):
    print(i,'=>',l[i])

0 => 3
1 => 7
2 => 2
3 => 9
4 => 8


In [125]:
l = [3,7,2,9,8]

for i,n in enumerate(l):
    print(i,'=>',n)

0 => 3
1 => 7
2 => 2
3 => 9
4 => 8


### random 라이브러리

In [126]:
import random

In [127]:
dir(random)

['BPF',
 'LOG4',
 'NV_MAGICCONST',
 'RECIP_BPF',
 'Random',
 'SG_MAGICCONST',
 'SystemRandom',
 'TWOPI',
 '_BuiltinMethodType',
 '_MethodType',
 '_Sequence',
 '_Set',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_acos',
 '_bisect',
 '_ceil',
 '_cos',
 '_e',
 '_exp',
 '_inst',
 '_itertools',
 '_log',
 '_pi',
 '_random',
 '_sha512',
 '_sin',
 '_sqrt',
 '_test',
 '_test_generator',
 '_urandom',
 '_warn',
 'betavariate',
 'choice',
 'choices',
 'expovariate',
 'gammavariate',
 'gauss',
 'getrandbits',
 'getstate',
 'lognormvariate',
 'normalvariate',
 'paretovariate',
 'randint',
 'random',
 'randrange',
 'sample',
 'seed',
 'setstate',
 'shuffle',
 'triangular',
 'uniform',
 'vonmisesvariate',
 'weibullvariate']

In [128]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [132]:
for i in range(10):
    print(random.randint(1,6))

2
3
3
2
1
5
6
6
1
6


### 연습문제
- 주사위 10번 던진 것을 한 게임이라고 하자.
- 위의 게임을 100번 했을 때의 결과를 2차원 리스트로 만드시오.
- (도전문제) 위 결과를 몽땅 리스트 컴프리헨션을 이용해 구해보시오.
- (도전문제) 한 게임에서 평균이 4이상이면 이긴 것이다. 몇 번 이겼나요?

In [133]:
import random

game = []
for i in range(10):
    game.append(random.randint(1,6))
    
game

[3, 2, 3, 1, 1, 1, 2, 5, 2, 6]

In [134]:
data = []

for j in range(100):
    game = []
    for i in range(10):
        game.append(random.randint(1,6))
    data.append(game)
    
data

[[2, 6, 1, 4, 6, 5, 2, 6, 2, 2],
 [1, 1, 6, 1, 3, 5, 6, 5, 4, 1],
 [1, 5, 5, 2, 4, 2, 3, 2, 5, 5],
 [6, 5, 1, 6, 4, 5, 6, 2, 1, 5],
 [4, 5, 5, 1, 6, 1, 6, 5, 6, 3],
 [1, 1, 5, 6, 4, 1, 2, 6, 5, 6],
 [2, 6, 1, 4, 4, 1, 6, 3, 4, 5],
 [1, 2, 3, 5, 6, 1, 3, 3, 4, 6],
 [2, 4, 4, 5, 4, 2, 4, 2, 2, 2],
 [3, 2, 6, 2, 2, 4, 1, 5, 2, 2],
 [5, 4, 1, 1, 1, 5, 3, 2, 1, 4],
 [1, 3, 4, 6, 3, 1, 6, 5, 2, 4],
 [3, 3, 5, 5, 6, 1, 2, 1, 2, 2],
 [6, 3, 4, 3, 2, 5, 3, 1, 5, 6],
 [6, 5, 2, 2, 6, 1, 2, 6, 6, 4],
 [5, 4, 6, 4, 4, 1, 5, 3, 5, 2],
 [6, 5, 6, 3, 6, 1, 2, 2, 6, 4],
 [4, 4, 4, 2, 6, 3, 1, 5, 2, 1],
 [3, 2, 2, 5, 2, 6, 6, 5, 4, 1],
 [4, 2, 5, 3, 4, 1, 6, 2, 5, 3],
 [2, 1, 3, 3, 5, 6, 6, 4, 6, 5],
 [1, 2, 2, 2, 4, 4, 6, 6, 1, 3],
 [5, 4, 4, 5, 1, 2, 3, 6, 1, 5],
 [1, 1, 3, 1, 5, 1, 6, 5, 4, 6],
 [2, 2, 4, 5, 4, 2, 1, 6, 2, 6],
 [6, 4, 4, 4, 1, 4, 4, 4, 2, 3],
 [6, 6, 1, 3, 3, 6, 2, 3, 1, 6],
 [1, 6, 3, 6, 4, 3, 5, 1, 1, 4],
 [6, 4, 1, 3, 2, 2, 3, 2, 1, 5],
 [5, 5, 3, 1, 2, 4, 1, 1, 4, 5],
 [1, 1, 6,

In [136]:
data = []

for j in range(100):
    data.append([random.randint(1,6) for i in range(10)])
    
data

[[3, 4, 3, 5, 5, 1, 5, 4, 2, 5],
 [2, 5, 4, 3, 4, 2, 3, 1, 5, 6],
 [5, 1, 1, 3, 5, 4, 2, 4, 1, 2],
 [2, 3, 4, 1, 3, 5, 3, 5, 5, 2],
 [2, 1, 5, 6, 3, 3, 2, 2, 3, 2],
 [2, 2, 6, 3, 1, 2, 3, 1, 5, 1],
 [4, 2, 1, 2, 2, 2, 4, 1, 3, 6],
 [4, 1, 3, 3, 3, 6, 4, 2, 3, 5],
 [3, 3, 4, 2, 4, 4, 5, 3, 1, 2],
 [5, 1, 2, 2, 3, 6, 4, 6, 2, 6],
 [3, 6, 3, 6, 4, 1, 6, 4, 3, 5],
 [1, 2, 1, 6, 4, 6, 3, 1, 1, 4],
 [3, 2, 4, 6, 6, 4, 4, 4, 6, 4],
 [3, 3, 2, 1, 6, 3, 2, 6, 5, 3],
 [6, 2, 3, 4, 1, 2, 5, 2, 4, 6],
 [2, 3, 6, 2, 4, 5, 4, 4, 1, 6],
 [6, 2, 6, 4, 2, 3, 3, 1, 1, 5],
 [1, 1, 4, 5, 4, 4, 2, 2, 4, 4],
 [1, 4, 3, 3, 6, 3, 5, 2, 5, 5],
 [4, 3, 2, 5, 3, 6, 2, 1, 6, 4],
 [4, 6, 5, 4, 1, 3, 5, 4, 3, 3],
 [1, 5, 1, 3, 3, 3, 1, 2, 6, 6],
 [2, 1, 2, 3, 5, 4, 3, 5, 4, 1],
 [1, 1, 2, 1, 6, 5, 5, 3, 6, 5],
 [1, 1, 5, 2, 4, 5, 6, 5, 1, 1],
 [3, 4, 4, 1, 1, 4, 1, 5, 3, 4],
 [5, 2, 2, 1, 6, 2, 3, 6, 6, 3],
 [1, 6, 3, 2, 2, 1, 1, 1, 3, 4],
 [4, 5, 5, 1, 1, 5, 2, 4, 3, 6],
 [6, 6, 6, 4, 1, 4, 6, 6, 2, 3],
 [5, 6, 1,

In [135]:
data = [[random.randint(1,6) for i in range(10)] for j in range(100)]
    
data

[[5, 1, 6, 3, 3, 3, 4, 5, 6, 4],
 [5, 4, 1, 1, 6, 6, 6, 1, 1, 1],
 [3, 3, 2, 4, 2, 5, 2, 6, 1, 3],
 [1, 2, 2, 4, 2, 5, 2, 2, 4, 6],
 [5, 2, 4, 5, 1, 1, 3, 6, 6, 4],
 [3, 4, 1, 1, 6, 1, 1, 6, 2, 6],
 [5, 4, 2, 3, 5, 5, 2, 3, 1, 4],
 [1, 6, 1, 1, 6, 4, 6, 6, 4, 2],
 [2, 2, 5, 5, 2, 6, 6, 2, 1, 3],
 [3, 2, 5, 1, 1, 6, 4, 2, 2, 1],
 [6, 6, 6, 2, 4, 3, 6, 4, 5, 2],
 [4, 4, 2, 6, 2, 6, 1, 3, 3, 4],
 [3, 5, 4, 5, 1, 1, 1, 1, 3, 2],
 [2, 5, 6, 4, 5, 6, 6, 4, 4, 6],
 [4, 2, 5, 3, 4, 2, 4, 6, 6, 1],
 [3, 6, 5, 2, 6, 1, 3, 2, 2, 5],
 [4, 6, 2, 3, 3, 3, 2, 6, 5, 2],
 [1, 4, 5, 1, 2, 1, 4, 3, 1, 3],
 [5, 4, 6, 6, 3, 3, 2, 2, 1, 6],
 [1, 1, 3, 3, 3, 2, 2, 4, 3, 4],
 [2, 5, 2, 4, 6, 2, 1, 3, 2, 2],
 [3, 2, 5, 6, 6, 1, 4, 2, 4, 5],
 [4, 5, 1, 2, 2, 6, 6, 4, 4, 1],
 [1, 2, 4, 6, 1, 5, 3, 3, 5, 3],
 [1, 2, 2, 4, 1, 1, 4, 4, 3, 2],
 [3, 5, 4, 5, 2, 6, 3, 5, 1, 6],
 [2, 6, 6, 6, 4, 3, 5, 1, 2, 1],
 [4, 6, 2, 2, 1, 3, 6, 2, 2, 3],
 [6, 6, 3, 4, 1, 1, 6, 3, 1, 2],
 [2, 3, 2, 5, 2, 6, 4, 2, 4, 1],
 [2, 5, 2,

In [138]:
n = 0
for game in data:
    if sum(game)/10 >= 4: n += 1
        
print(n)

15


In [139]:
result = []
for game in data:
    if sum(game)/10 >= 4: result.append(1)
    else: result.append(0)
        
print(sum(result))

15


### re 모듈 (정규표현식)
- regular expression

In [140]:
import re

In [155]:
p = re.compile('0[0-9]{2}-[0-9]{3,4}-[0-9]{4}')

In [159]:
print(p.findall('010-1234-5678'))

['010-1234-5678']


### datetime 모듈

In [160]:
import datetime

In [161]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [162]:
d = datetime.date(2020,9,7)
print(d)

2020-09-07


In [166]:
wday = ['월','화','수','목','금','토','일']
wday[d.weekday()]

'월'

In [165]:
help(d.weekday)

Help on built-in function weekday:

weekday(...) method of datetime.date instance
    Return the day of the week represented by the date.
    Monday == 0 ... Sunday == 6



### 연습문제
- iris 데이터를 2차원 리스트로 불러오시오.
- 앞 10개의 샘플(행)을 뽑아내시오.
- 뒷 10개의 샘플(행)을 뽑아내시오.
- 앞의 속성(열) 4개를 X 로 뽑아내시오.
- 마지막 속성(열)을 y 로 뽑아내시오.
- (도전) X 에서 가장 중앙의 2x2 형태를 뽑아내시오

In [169]:
f = open('iris.csv')

s = f.readline()
header = s.strip().split(',')

labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris = []

for line in f:
    l = line.strip().split(',')
    l[0] = float(l[0])
    l[1] = float(l[1])
    l[2] = float(l[2])
    l[3] = float(l[3])
    l[4] = labels.index(l[4])
    iris.append(l)

f.close()

iris

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.4, 3.7, 1.5, 0.2, 0],
 [4.8, 3.4, 1.6, 0.2, 0],
 [4.8, 3.0, 1.4, 0.1, 0],
 [4.3, 3.0, 1.1, 0.1, 0],
 [5.8, 4.0, 1.2, 0.2, 0],
 [5.7, 4.4, 1.5, 0.4, 0],
 [5.4, 3.9, 1.3, 0.4, 0],
 [5.1, 3.5, 1.4, 0.3, 0],
 [5.7, 3.8, 1.7, 0.3, 0],
 [5.1, 3.8, 1.5, 0.3, 0],
 [5.4, 3.4, 1.7, 0.2, 0],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.6, 3.6, 1.0, 0.2, 0],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.0, 3.0, 1.6, 0.2, 0],
 [5.0, 3.4, 1.6, 0.4, 0],
 [5.2, 3.5, 1.5, 0.2, 0],
 [5.2, 3.4, 1.4, 0.2, 0],
 [4.7, 3.2, 1.6, 0.2, 0],
 [4.8, 3.1, 1.6, 0.2, 0],
 [5.4, 3.4, 1.5, 0.4, 0],
 [5.2, 4.1, 1.5, 0.1, 0],
 [5.5, 4.2, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.0, 3.2, 1.2, 0.2, 0],
 [5.5, 3.5, 1.3, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.4, 3.0, 

In [172]:
iris[:10]

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0]]

In [173]:
iris[-10:]

[[6.7, 3.1, 5.6, 2.4, 2],
 [6.9, 3.1, 5.1, 2.3, 2],
 [5.8, 2.7, 5.1, 1.9, 2],
 [6.8, 3.2, 5.9, 2.3, 2],
 [6.7, 3.3, 5.7, 2.5, 2],
 [6.7, 3.0, 5.2, 2.3, 2],
 [6.3, 2.5, 5.0, 1.9, 2],
 [6.5, 3.0, 5.2, 2.0, 2],
 [6.2, 3.4, 5.4, 2.3, 2],
 [5.9, 3.0, 5.1, 1.8, 2]]

In [174]:
X = []
for i in iris:
    X.append(i[:4]) # 슬라이싱을 적용하면 데이터가 copy 된다
    
X
# X = [i[:4] for i in iris]

[[5.1, 3.5, 1.4, 0.2],
 [4.9, 3.0, 1.4, 0.2],
 [4.7, 3.2, 1.3, 0.2],
 [4.6, 3.1, 1.5, 0.2],
 [5.0, 3.6, 1.4, 0.2],
 [5.4, 3.9, 1.7, 0.4],
 [4.6, 3.4, 1.4, 0.3],
 [5.0, 3.4, 1.5, 0.2],
 [4.4, 2.9, 1.4, 0.2],
 [4.9, 3.1, 1.5, 0.1],
 [5.4, 3.7, 1.5, 0.2],
 [4.8, 3.4, 1.6, 0.2],
 [4.8, 3.0, 1.4, 0.1],
 [4.3, 3.0, 1.1, 0.1],
 [5.8, 4.0, 1.2, 0.2],
 [5.7, 4.4, 1.5, 0.4],
 [5.4, 3.9, 1.3, 0.4],
 [5.1, 3.5, 1.4, 0.3],
 [5.7, 3.8, 1.7, 0.3],
 [5.1, 3.8, 1.5, 0.3],
 [5.4, 3.4, 1.7, 0.2],
 [5.1, 3.7, 1.5, 0.4],
 [4.6, 3.6, 1.0, 0.2],
 [5.1, 3.3, 1.7, 0.5],
 [4.8, 3.4, 1.9, 0.2],
 [5.0, 3.0, 1.6, 0.2],
 [5.0, 3.4, 1.6, 0.4],
 [5.2, 3.5, 1.5, 0.2],
 [5.2, 3.4, 1.4, 0.2],
 [4.7, 3.2, 1.6, 0.2],
 [4.8, 3.1, 1.6, 0.2],
 [5.4, 3.4, 1.5, 0.4],
 [5.2, 4.1, 1.5, 0.1],
 [5.5, 4.2, 1.4, 0.2],
 [4.9, 3.1, 1.5, 0.1],
 [5.0, 3.2, 1.2, 0.2],
 [5.5, 3.5, 1.3, 0.2],
 [4.9, 3.1, 1.5, 0.1],
 [4.4, 3.0, 1.3, 0.2],
 [5.1, 3.4, 1.5, 0.2],
 [5.0, 3.5, 1.3, 0.3],
 [4.5, 2.3, 1.3, 0.3],
 [4.4, 3.2, 1.3, 0.2],
 [5.0, 3.5,

In [176]:
y = []

for i in iris:
    y.append(i[-1])
    
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [181]:
data = []
for i in X[74:76]:
    data.append(i[1:3])
    
data

[[2.9, 4.3], [3.0, 4.4]]

In [182]:
data = [i[1:3] for i in X[74:76]]
    
data

[[2.9, 4.3], [3.0, 4.4]]

In [183]:
import numpy as np

In [184]:
X = np.array(X)
X[74:76, 1:3]

array([[2.9, 4.3],
       [3. , 4.4]])

### 연습문제
- http://search.danawa.com/dsearch.php?k1=%EB%85%B8%ED%8A%B8%EB%B6%81&module=goods&act=dispMain
```
43.1cm(17인치) / 인텔 / 코어i7-10세대 / 아이스레이크 / i7-1065G7 / 1.3GHz(3.9GHz) / 쿼드코어 / 2560x1600(WQXGA) / 광시야각(IPS) / 슬림형 베젤 / DDR4 / 8GB / M.2(NVMe) / 256GB / Iris Plus Graphics / 802.11ax(Wi-Fi 6) / 블루투스 / HDMI / 웹캠(HD) / 썬더볼트3 : 1개 / USB 3.1 Type-C / USB 3.1 / UFS / MicroSD카드 / 숫자 키패드 / 키보드 라이트 / MIL-STD / 지문 인식 / USB-PD / 배터리 : 80Wh / 운영체제 : 미포함(프리도스) / 두께 : 17.4mm / 무게 : 1.35kg / 일반유통상품 / 용도 : 사무/인강용 , 휴대용 / 색상: 화이트
```
- 리스트로 데이터를 분해하시오.

In [187]:
s = '''43.1cm(17인치) / 인텔 / 코어i7-10세대 / 아이스레이크 / i7-1065G7 / 1.3GHz(3.9GHz) / 쿼드코어 / 2560x1600(WQXGA) / 광시야각(IPS) / 슬림형 베젤 / DDR4 / 8GB / M.2(NVMe) / 256GB / Iris Plus Graphics / 802.11ax(Wi-Fi 6) / 블루투스 / HDMI / 웹캠(HD) / 썬더볼트3 : 1개 / USB 3.1 Type-C / USB 3.1 / UFS / MicroSD카드 / 숫자 키패드 / 키보드 라이트 / MIL-STD / 지문 인식 / USB-PD / 배터리 : 80Wh / 운영체제 : 미포함(프리도스) / 두께 : 17.4mm / 무게 : 1.35kg / 일반유통상품 / 용도 : 사무/인강용 , 휴대용 / 색상: 화이트'''

In [188]:
s

'43.1cm(17인치) / 인텔 / 코어i7-10세대 / 아이스레이크 / i7-1065G7 / 1.3GHz(3.9GHz) / 쿼드코어 / 2560x1600(WQXGA) / 광시야각(IPS) / 슬림형 베젤 / DDR4 / 8GB / M.2(NVMe) / 256GB / Iris Plus Graphics / 802.11ax(Wi-Fi 6) / 블루투스 / HDMI / 웹캠(HD) / 썬더볼트3 : 1개 / USB 3.1 Type-C / USB 3.1 / UFS / MicroSD카드 / 숫자 키패드 / 키보드 라이트 / MIL-STD / 지문 인식 / USB-PD / 배터리 : 80Wh / 운영체제 : 미포함(프리도스) / 두께 : 17.4mm / 무게 : 1.35kg / 일반유통상품 / 용도 : 사무/인강용 , 휴대용 / 색상: 화이트'

In [190]:
s.strip().split(' / ')

36

In [191]:
[i.strip() for i in s.strip().split(' / ')]

['43.1cm(17인치)',
 '인텔',
 '코어i7-10세대',
 '아이스레이크',
 'i7-1065G7',
 '1.3GHz(3.9GHz)',
 '쿼드코어',
 '2560x1600(WQXGA)',
 '광시야각(IPS)',
 '슬림형 베젤',
 'DDR4',
 '8GB',
 'M.2(NVMe)',
 '256GB',
 'Iris Plus Graphics',
 '802.11ax(Wi-Fi 6)',
 '블루투스',
 'HDMI',
 '웹캠(HD)',
 '썬더볼트3 : 1개',
 'USB 3.1 Type-C',
 'USB 3.1',
 'UFS',
 'MicroSD카드',
 '숫자 키패드',
 '키보드 라이트',
 'MIL-STD',
 '지문 인식',
 'USB-PD',
 '배터리 : 80Wh',
 '운영체제 : 미포함(프리도스)',
 '두께 : 17.4mm',
 '무게 : 1.35kg',
 '일반유통상품',
 '용도 : 사무/인강용 , 휴대용',
 '색상: 화이트']

### 연습문제
- iris 데이터(X)에서 각 속성(열)의 평균을 구하시오
- X 에서 첫번째 열의 값이 7 이상인 샘플을 골라내시오
- y 값이 1인 샘플을 골라내시오
- (도전) iris 데이터 에서 랜덤하게 샘플 10개를 뽑으시오 (중복 허용, random.randint() 함수 사용)

In [193]:
m = 0

for i in X:
    m += i[0]
    
m = m/150
m

5.843333333333335

In [194]:
m = [0,0,0,0]

for i in X:
    m[0] += i[0]
    m[1] += i[1]
    m[2] += i[2]
    m[3] += i[3]
    
m = [i/150 for i in m]
m

[5.843333333333335, 3.0540000000000007, 3.7586666666666693, 1.1986666666666672]

In [195]:
m = [0,0,0,0]

for i in X:
    for j in range(4):
        m[j] += i[j]
    
m = [i/150 for i in m]
m

[5.843333333333335, 3.0540000000000007, 3.7586666666666693, 1.1986666666666672]

In [198]:
result = []

for i in iris:
    if i[0]>=7: result.append(i)
        
result

[[7.0, 3.2, 4.7, 1.4, 1],
 [7.1, 3.0, 5.9, 2.1, 2],
 [7.6, 3.0, 6.6, 2.1, 2],
 [7.3, 2.9, 6.3, 1.8, 2],
 [7.2, 3.6, 6.1, 2.5, 2],
 [7.7, 3.8, 6.7, 2.2, 2],
 [7.7, 2.6, 6.9, 2.3, 2],
 [7.7, 2.8, 6.7, 2.0, 2],
 [7.2, 3.2, 6.0, 1.8, 2],
 [7.2, 3.0, 5.8, 1.6, 2],
 [7.4, 2.8, 6.1, 1.9, 2],
 [7.9, 3.8, 6.4, 2.0, 2],
 [7.7, 3.0, 6.1, 2.3, 2]]

In [199]:
[i for i in iris if i[0]>=7]

[[7.0, 3.2, 4.7, 1.4, 1],
 [7.1, 3.0, 5.9, 2.1, 2],
 [7.6, 3.0, 6.6, 2.1, 2],
 [7.3, 2.9, 6.3, 1.8, 2],
 [7.2, 3.6, 6.1, 2.5, 2],
 [7.7, 3.8, 6.7, 2.2, 2],
 [7.7, 2.6, 6.9, 2.3, 2],
 [7.7, 2.8, 6.7, 2.0, 2],
 [7.2, 3.2, 6.0, 1.8, 2],
 [7.2, 3.0, 5.8, 1.6, 2],
 [7.4, 2.8, 6.1, 1.9, 2],
 [7.9, 3.8, 6.4, 2.0, 2],
 [7.7, 3.0, 6.1, 2.3, 2]]

In [200]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [201]:
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [202]:
for i in range(150):
    if y[i]==1: print(X[i])

[7.  3.2 4.7 1.4]
[6.4 3.2 4.5 1.5]
[6.9 3.1 4.9 1.5]
[5.5 2.3 4.  1.3]
[6.5 2.8 4.6 1.5]
[5.7 2.8 4.5 1.3]
[6.3 3.3 4.7 1.6]
[4.9 2.4 3.3 1. ]
[6.6 2.9 4.6 1.3]
[5.2 2.7 3.9 1.4]
[5.  2.  3.5 1. ]
[5.9 3.  4.2 1.5]
[6.  2.2 4.  1. ]
[6.1 2.9 4.7 1.4]
[5.6 2.9 3.6 1.3]
[6.7 3.1 4.4 1.4]
[5.6 3.  4.5 1.5]
[5.8 2.7 4.1 1. ]
[6.2 2.2 4.5 1.5]
[5.6 2.5 3.9 1.1]
[5.9 3.2 4.8 1.8]
[6.1 2.8 4.  1.3]
[6.3 2.5 4.9 1.5]
[6.1 2.8 4.7 1.2]
[6.4 2.9 4.3 1.3]
[6.6 3.  4.4 1.4]
[6.8 2.8 4.8 1.4]
[6.7 3.  5.  1.7]
[6.  2.9 4.5 1.5]
[5.7 2.6 3.5 1. ]
[5.5 2.4 3.8 1.1]
[5.5 2.4 3.7 1. ]
[5.8 2.7 3.9 1.2]
[6.  2.7 5.1 1.6]
[5.4 3.  4.5 1.5]
[6.  3.4 4.5 1.6]
[6.7 3.1 4.7 1.5]
[6.3 2.3 4.4 1.3]
[5.6 3.  4.1 1.3]
[5.5 2.5 4.  1.3]
[5.5 2.6 4.4 1.2]
[6.1 3.  4.6 1.4]
[5.8 2.6 4.  1.2]
[5.  2.3 3.3 1. ]
[5.6 2.7 4.2 1.3]
[5.7 3.  4.2 1.2]
[5.7 2.9 4.2 1.3]
[6.2 2.9 4.3 1.3]
[5.1 2.5 3.  1.1]
[5.7 2.8 4.1 1.3]
