## 파이썬 데이터분석
# Numpy 어레이(array) 마음대로 잘라내기

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
iris = np.loadtxt('iris.csv', delimiter=',', skiprows=1, usecols=[0,1,2,3])

In [3]:
iris.shape, iris.dtype

((150, 4), dtype('float64'))

In [9]:
y=np.array([i//50 for i in range(150) ])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
y = np.array([0]*50+[1]*50+[2]*50)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
y = np.zeros(150)
y[50:100] = 1
y[100:] = 2
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [2]:
help(np.loadtxt)

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
       

In [9]:
iris[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
y[:5]

array([0, 0, 0, 0, 0])

### 팬시 색인
- 행 부분에 목록을 넣으면 해당 행들을 골라낼 수 있다

In [11]:
a = np.array([9,3,7,5,6])
a

array([9, 3, 7, 5, 6])

In [6]:
a[::2]

array([9, 7, 6])

In [7]:
a[-3:]

array([7, 5, 6])

In [8]:
a[0]   +   a[-2:] # 9 + np.array([5,6])

array([14, 15])

In [11]:
l = []
l.append(a[0])
l = l + list(a[-2:])
np.array(l)

array([9, 5, 6])

In [4]:
a = np.array([9,3,7,5,6])
a

array([9, 3, 7, 5, 6])

In [5]:
a[::2]

array([9, 7, 6])

In [12]:
a[ [0,3,4] ] # 팬시 색인

array([9, 5, 6])

In [13]:
a[ [0,-2,-1] ] # 팬시 색인

array([9, 5, 6])

In [15]:
a[[2,4]]

array([7, 6])

In [27]:
a[ [0,1,3,4] ] # [a[0], a[1], a[3], a[4]]

array([9, 3, 5, 6])

In [6]:
mat = np.arange(12).reshape(4,3)
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
mat[[0,3]]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [30]:
mat[[3,2,1,0]]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5],
       [ 0,  1,  2]])

In [31]:
mat[[0,0,0,0]]

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [8]:
#mat[np.random.permutation(range(4))]
np.random.permutation(mat)

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [16]:
mat[[1,0,0,1,2,2,2,2,2,2,2,2,2,2]]

array([[3, 4, 5],
       [0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8],
       [6, 7, 8]])

- 열에 대해서도 팬시색인을 적용할 수 있다

In [33]:
mat[:, [0,-1]]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [9]:
mat[:,[2,1,0]]

array([[ 2,  1,  0],
       [ 5,  4,  3],
       [ 8,  7,  6],
       [11, 10,  9]])

In [11]:
a = np.array([1,2,3])

In [23]:
a[0]

1

In [22]:
a[[0]]

array([1])

In [12]:
a[[0,1]]

array([1, 2])

In [15]:
iris[[0,50,100]]

array([[5.1, 3.5, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.3, 3.3, 6. , 2.5]])

In [17]:
iris[ [0,2,4] ] # 행번호 0,2,4 를 골라냄

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [18]:
iris[:, [0,3]]

array([[5.1, 0.2],
       [4.9, 0.2],
       [4.7, 0.2],
       [4.6, 0.2],
       [5. , 0.2],
       [5.4, 0.4],
       [4.6, 0.3],
       [5. , 0.2],
       [4.4, 0.2],
       [4.9, 0.1],
       [5.4, 0.2],
       [4.8, 0.2],
       [4.8, 0.1],
       [4.3, 0.1],
       [5.8, 0.2],
       [5.7, 0.4],
       [5.4, 0.4],
       [5.1, 0.3],
       [5.7, 0.3],
       [5.1, 0.3],
       [5.4, 0.2],
       [5.1, 0.4],
       [4.6, 0.2],
       [5.1, 0.5],
       [4.8, 0.2],
       [5. , 0.2],
       [5. , 0.4],
       [5.2, 0.2],
       [5.2, 0.2],
       [4.7, 0.2],
       [4.8, 0.2],
       [5.4, 0.4],
       [5.2, 0.1],
       [5.5, 0.2],
       [4.9, 0.1],
       [5. , 0.2],
       [5.5, 0.2],
       [4.9, 0.1],
       [4.4, 0.2],
       [5.1, 0.2],
       [5. , 0.3],
       [4.5, 0.3],
       [4.4, 0.2],
       [5. , 0.6],
       [5.1, 0.4],
       [4.8, 0.3],
       [5.1, 0.2],
       [4.6, 0.2],
       [5.3, 0.2],
       [5. , 0.2],
       [7. , 1.4],
       [6.4, 1.5],
       [6.9,

In [19]:
# 각 품종별 첫번째 샘플을 팬시색인으로 뽑으시오
iris[[0,50,100]]

array([[5.1, 3.5, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.3, 3.3, 6. , 2.5]])

In [20]:
iris[ [4,3,2,1,0] ]

array([[5. , 3.6, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2]])

In [37]:
iris[ [0,0,1,1] ] # 한 행을 여러번 불러올 수도 있다

array([[5.1, 3.5, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

- 마찬가지 방법으로 열 부분을 골라낼 수 있다

In [40]:
iris[:, [0,2,3] ]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2],
       [5.4, 1.7, 0.4],
       [4.6, 1.4, 0.3],
       [5. , 1.5, 0.2],
       [4.4, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5.4, 1.5, 0.2],
       [4.8, 1.6, 0.2],
       [4.8, 1.4, 0.1],
       [4.3, 1.1, 0.1],
       [5.8, 1.2, 0.2],
       [5.7, 1.5, 0.4],
       [5.4, 1.3, 0.4],
       [5.1, 1.4, 0.3],
       [5.7, 1.7, 0.3],
       [5.1, 1.5, 0.3],
       [5.4, 1.7, 0.2],
       [5.1, 1.5, 0.4],
       [4.6, 1. , 0.2],
       [5.1, 1.7, 0.5],
       [4.8, 1.9, 0.2],
       [5. , 1.6, 0.2],
       [5. , 1.6, 0.4],
       [5.2, 1.5, 0.2],
       [5.2, 1.4, 0.2],
       [4.7, 1.6, 0.2],
       [4.8, 1.6, 0.2],
       [5.4, 1.5, 0.4],
       [5.2, 1.5, 0.1],
       [5.5, 1.4, 0.2],
       [4.9, 1.5, 0.1],
       [5. , 1.2, 0.2],
       [5.5, 1.3, 0.2],
       [4.9, 1.5, 0.1],
       [4.4, 1.3, 0.2],
       [5.1, 1.5, 0.2],
       [5. , 1.3, 0.3],
       [4.5, 1.3

In [24]:
iris[:,[3,2,1,0]] # iris[:,::-1]

array([[0.2, 1.4, 3.5, 5.1],
       [0.2, 1.4, 3. , 4.9],
       [0.2, 1.3, 3.2, 4.7],
       [0.2, 1.5, 3.1, 4.6],
       [0.2, 1.4, 3.6, 5. ],
       [0.4, 1.7, 3.9, 5.4],
       [0.3, 1.4, 3.4, 4.6],
       [0.2, 1.5, 3.4, 5. ],
       [0.2, 1.4, 2.9, 4.4],
       [0.1, 1.5, 3.1, 4.9],
       [0.2, 1.5, 3.7, 5.4],
       [0.2, 1.6, 3.4, 4.8],
       [0.1, 1.4, 3. , 4.8],
       [0.1, 1.1, 3. , 4.3],
       [0.2, 1.2, 4. , 5.8],
       [0.4, 1.5, 4.4, 5.7],
       [0.4, 1.3, 3.9, 5.4],
       [0.3, 1.4, 3.5, 5.1],
       [0.3, 1.7, 3.8, 5.7],
       [0.3, 1.5, 3.8, 5.1],
       [0.2, 1.7, 3.4, 5.4],
       [0.4, 1.5, 3.7, 5.1],
       [0.2, 1. , 3.6, 4.6],
       [0.5, 1.7, 3.3, 5.1],
       [0.2, 1.9, 3.4, 4.8],
       [0.2, 1.6, 3. , 5. ],
       [0.4, 1.6, 3.4, 5. ],
       [0.2, 1.5, 3.5, 5.2],
       [0.2, 1.4, 3.4, 5.2],
       [0.2, 1.6, 3.2, 4.7],
       [0.2, 1.6, 3.1, 4.8],
       [0.4, 1.5, 3.4, 5.4],
       [0.1, 1.5, 4.1, 5.2],
       [0.2, 1.4, 4.2, 5.5],
       [0.1, 1

- 아이리스에서 샘플을 10개 뽑아라

In [27]:
# 방법1
np.random.permutation(iris)[:10]

array([[6.1, 2.8, 4.7, 1.2],
       [6.3, 3.3, 6. , 2.5],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.9, 4.3, 1.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 3.5, 1.3, 0.2],
       [4.8, 3.1, 1.6, 0.2]])

In [16]:
# 방법2
idx = np.random.randint(150, size=10)
idx

array([ 97,  23,  10,  17,  30, 130,   9,  39,  96,  82])

In [17]:
iris[idx]

array([[6.2, 2.9, 4.3, 1.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.5, 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.8, 2.7, 3.9, 1.2]])

In [20]:
y[idx]

array([1, 0, 0, 0, 0, 2, 0, 0, 1, 1])

In [56]:
# 중복되지 않는 샘플 10개를 뽑으시오
idx = np.random.permutation(range(150))[:10]
idx

array([126, 118,   8,   9, 134,  76,  68,  12, 116,  91])

In [57]:
iris[idx]

array([[6.2, 2.8, 4.8, 1.8],
       [7.7, 2.6, 6.9, 2.3],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [6.1, 2.6, 5.6, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.2, 2.2, 4.5, 1.5],
       [4.8, 3. , 1.4, 0.1],
       [6.5, 3. , 5.5, 1.8],
       [6.1, 3. , 4.6, 1.4]])

In [33]:
np.random.permutation(iris)[:10]

array([[5.1, 3.5, 1.4, 0.3],
       [4.7, 3.2, 1.3, 0.2],
       [6.6, 2.9, 4.6, 1.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.6, 2.5, 3.9, 1.1],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [34]:
iris[np.random.choice(range(150), size=10, replace=False)]

array([[5.1, 2.5, 3. , 1.1],
       [4.9, 3. , 1.4, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [6. , 2.9, 4.5, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.7, 1. ],
       [6.8, 3. , 5.5, 2.1],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.6, 1. , 0.2],
       [5.5, 2.5, 4. , 1.3]])

In [35]:
idx = np.random.randint(150, size=10)
idx

array([127, 136, 139,  89, 108, 131,  59, 137, 113, 115])

In [36]:
iris[[ 81,  23,  57,  39,  47, 134,  14,  24,  57,  66]]

array([[5.5, 2.4, 3.7, 1. ],
       [5.1, 3.3, 1.7, 0.5],
       [4.9, 2.4, 3.3, 1. ],
       [5.1, 3.4, 1.5, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.8, 4. , 1.2, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [5.6, 3. , 4.5, 1.5]])

In [37]:
iris[idx]

array([[6.1, 3. , 4.9, 1.8],
       [6.3, 3.4, 5.6, 2.4],
       [6.9, 3.1, 5.4, 2.1],
       [5.5, 2.5, 4. , 1.3],
       [6.7, 2.5, 5.8, 1.8],
       [7.9, 3.8, 6.4, 2. ],
       [5.2, 2.7, 3.9, 1.4],
       [6.4, 3.1, 5.5, 1.8],
       [5.7, 2.5, 5. , 2. ],
       [6.4, 3.2, 5.3, 2.3]])

In [40]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [41]:
y[idx]

array([2., 2., 2., 1., 2., 2., 1., 2., 2., 2.])

### 연습문제
- 아래의 어레이 a 에서 a[[0,2,4,6,1,3,5,7]] 의 결과를 확인하고 해석해 보시오
- 아이리스 데이터를 이것과 비슷하게 뽑아내시오.
- 팬시색인을 이용

In [2]:
import numpy as np

In [4]:
a = np.arange(24).reshape(8,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a[[0,2,4,6,1,3,5,7]]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [10]:
iris = np.loadtxt('iris.csv', delimiter=',', skiprows=1, usecols=[0,1,2,3])

In [16]:
iris[list(range(0,150,2)) + list(range(1,150,2))]

array([[5.1, 3.5, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.4, 1.4, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.2, 4.1, 1.5, 0.1],
       [4.9, 3.1, 1.5, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5.1, 3.8, 1.9, 0.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 2. , 3.5, 1. ],
       [6. , 2.2, 4. , 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.2, 2

In [15]:
list(range(0,150,2)) + list(range(1,150,2))

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 1,
 3,
 5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49,
 51,
 53,
 55,
 57,
 59,
 61,
 63,
 65,
 67,
 69,
 71,
 73,
 75,
 77,
 79,
 81,
 83,
 85,
 87,
 89,
 91,
 93,
 95,
 97,
 99,
 101,
 103,
 105,
 107,
 109,
 111,
 113,
 115,
 117,
 119,
 121,
 123,
 125,
 127,
 129,
 131,
 133,
 135,
 137,
 139,
 141,
 143,
 145,
 147,
 149]

In [18]:
iris[[0,10,11,20,21,0]]

array([[5.1, 3.5, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.1, 3.5, 1.4, 0.2]])

In [19]:
data = np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
label = np.array(['친구','가족','친구'])
label

array(['친구', '가족', '친구'], dtype='<U2')

In [46]:
data[[0,2]]

array([[1, 2],
       [5, 6]])

In [47]:
label[[0,2]]

array(['친구', '친구'], dtype='<U2')

- 아래와 같이 행과 열에 모두 목록을 넣으면, 쌍으로 위치를 지정하게 된다

In [41]:
iris[ [0,2,3], [0,2,3] ] # (0,0), (2,2), (3,3) 세 위치의 값을 얻는다

array([5.1, 1.3, 0.2])

### 연습문제
- 아이리스 데이터에서, 첫번째 속성(sepal length)의 값이 평균값 보다 큰 샘플들을 뽑아내시오.
- 문제1) 파이썬의 일반적인 방법으로 풀어보시오.
- 문제2) 일반적인 방법 이외에, 먼저 해당 인덱스를 먼저 알아낸 다음 팬시색인을 적용해 보시오.

In [21]:
iris_labels = ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
iris = np.loadtxt('iris.csv', skiprows=1, delimiter=',',
                  converters={4: lambda s: iris_labels.index(s.decode())})