### 연습문제
- 아래는 학생들의 성적표이다.
- 각 과목의 가중치 W 를 주어 학생별 평균을 구하려고 한다.
- 문제1) numpy 의 곱셈을 이용하는 방법
- 문제2) 행렬곱을 이용하는 방법

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
score = np.random.randint(50,100,size=[100,3])
W = np.array([1, 0.5, 0.7])

display(score, W)

array([[92, 81, 70],
       [63, 64, 91],
       [89, 99, 61],
       [52, 95, 92],
       [99, 94, 65],
       [64, 99, 87],
       [60, 72, 86],
       [99, 86, 55],
       [94, 99, 56],
       [51, 78, 58],
       [89, 52, 75],
       [90, 50, 57],
       [59, 93, 81],
       [97, 51, 82],
       [91, 81, 74],
       [66, 85, 97],
       [55, 59, 76],
       [94, 82, 67],
       [50, 90, 81],
       [96, 60, 79],
       [89, 98, 52],
       [65, 67, 91],
       [85, 88, 98],
       [74, 84, 50],
       [99, 88, 74],
       [65, 57, 69],
       [77, 63, 64],
       [92, 84, 53],
       [64, 92, 58],
       [63, 80, 78],
       [51, 72, 97],
       [80, 92, 77],
       [73, 68, 83],
       [52, 70, 85],
       [68, 55, 54],
       [78, 91, 63],
       [90, 95, 55],
       [71, 92, 70],
       [97, 90, 55],
       [92, 90, 51],
       [64, 52, 85],
       [54, 78, 88],
       [55, 72, 78],
       [53, 62, 67],
       [66, 90, 50],
       [75, 55, 63],
       [83, 73, 55],
       [60, 9

array([1. , 0.5, 0.7])

In [4]:
(score*W).mean(axis=1)

array([60.5       , 52.9       , 60.4       , 54.63333333, 63.83333333,
       58.13333333, 52.06666667, 60.16666667, 60.9       , 43.53333333,
       55.83333333, 51.63333333, 54.06666667, 59.96666667, 61.1       ,
       58.8       , 45.9       , 60.63333333, 50.56666667, 60.43333333,
       58.13333333, 54.06666667, 65.86666667, 50.33333333, 64.93333333,
       47.26666667, 51.1       , 57.03333333, 50.2       , 52.53333333,
       51.63333333, 59.96666667, 55.03333333, 48.83333333, 44.43333333,
       55.86666667, 58.66666667, 55.33333333, 60.16666667, 57.56666667,
       49.83333333, 51.53333333, 48.53333333, 43.63333333, 48.66666667,
       48.86666667, 52.66666667, 51.03333333, 62.6       , 46.23333333,
       62.2       , 50.8       , 52.93333333, 65.9       , 64.13333333,
       67.56666667, 64.06666667, 45.        , 55.56666667, 44.86666667,
       66.76666667, 58.4       , 57.3       , 50.5       , 48.8       ,
       58.36666667, 64.43333333, 56.13333333, 50.6       , 60.36

In [6]:
(score@W)/3

array([60.5       , 52.9       , 60.4       , 54.63333333, 63.83333333,
       58.13333333, 52.06666667, 60.16666667, 60.9       , 43.53333333,
       55.83333333, 51.63333333, 54.06666667, 59.96666667, 61.1       ,
       58.8       , 45.9       , 60.63333333, 50.56666667, 60.43333333,
       58.13333333, 54.06666667, 65.86666667, 50.33333333, 64.93333333,
       47.26666667, 51.1       , 57.03333333, 50.2       , 52.53333333,
       51.63333333, 59.96666667, 55.03333333, 48.83333333, 44.43333333,
       55.86666667, 58.66666667, 55.33333333, 60.16666667, 57.56666667,
       49.83333333, 51.53333333, 48.53333333, 43.63333333, 48.66666667,
       48.86666667, 52.66666667, 51.03333333, 62.6       , 46.23333333,
       62.2       , 50.8       , 52.93333333, 65.9       , 64.13333333,
       67.56666667, 64.06666667, 45.        , 55.56666667, 44.86666667,
       66.76666667, 58.4       , 57.3       , 50.5       , 48.8       ,
       58.36666667, 64.43333333, 56.13333333, 50.6       , 60.36

In [8]:
W = np.array([[1,0.5],[0.5,0.9],[0.7,0.6]])
W

array([[1. , 0.5],
       [0.5, 0.9],
       [0.7, 0.6]])

In [9]:
score@W

array([[181.5, 160.9],
       [158.7, 143.7],
       [181.2, 170.2],
       [163.9, 166.7],
       [191.5, 173.1],
       [174.4, 173.3],
       [156.2, 146.4],
       [180.5, 159.9],
       [182.7, 169.7],
       [130.6, 130.5],
       [167.5, 136.3],
       [154.9, 124.2],
       [162.2, 161.8],
       [179.9, 143.6],
       [183.3, 162.8],
       [176.4, 167.7],
       [137.7, 126.2],
       [181.9, 161. ],
       [151.7, 154.6],
       [181.3, 149.4],
       [174.4, 163.9],
       [162.2, 147.4],
       [197.6, 180.5],
       [151. , 142.6],
       [194.8, 173.1],
       [141.8, 125.2],
       [153.3, 133.6],
       [171.1, 153.4],
       [150.6, 149.6],
       [157.6, 150.3],
       [154.9, 148.5],
       [179.9, 169. ],
       [165.1, 147.5],
       [146.5, 140. ],
       [133.3, 115.9],
       [167.6, 158.7],
       [176. , 163.5],
       [166. , 160.3],
       [180.5, 162.5],
       [172.7, 157.6],
       [149.5, 129.8],
       [154.6, 150. ],
       [145.6, 139.1],
       [130