### 연습문제

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.zeros([5,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# a+X 의 결과가 아래와 같도록 X 를 구하시오
1 2 3 4 5
1 2 3 4 5
1 2 3 4 5
1 2 3 4 5
1 2 3 4 5

In [4]:
X = [1,2,3,4,5]
a+X

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [5]:
X = np.array([1,2,3,4,5])
a+X

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [ ]:
# a+X 의 결과가 아래와 같도록 X 를 구하시오
1 1 1 1 1
2 2 2 2 2
3 3 3 3 3
4 4 4 4 4
5 5 5 5 5

In [6]:
X = [[1],[2],[3],[4],[5]]
a+X

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [7]:
X = np.array([1,2,3,4,5]).reshape(5,1)
a+X

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [8]:
X

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [3]:
# images 는 (100,480,640,3) 형태의 컬러이미지 묶음이다.
# (480,3) 형태인 필터 f 를 곱하려고 한다. 방법은?

In [16]:
f = np.random.randn(480,3)
f.shape

(480, 3)

In [17]:
images = np.random.randint(256, size=[100,480,640,3])
f = f.reshape(480,1,3)
images*f

array([[[[-5.99902864e+01,  6.43598141e+01,  2.47180543e+01],
         [-1.30693124e+02,  6.37349615e+01,  6.38781178e+01],
         [-1.70686648e+02,  8.12308333e+00,  5.22134180e+01],
         ...,
         [-8.14153887e+01,  4.37396795e+00,  4.77697229e+01],
         [-1.18552233e+02,  4.81136474e+01,  9.16512125e+00],
         [-4.28502046e+00,  2.31195449e+01,  1.83302425e+01]],

        [[ 1.11288941e+01,  2.93225848e+01, -5.13549791e+02],
         [ 1.27467510e+00,  4.55774959e+01, -2.97649267e+02],
         [ 4.85357057e+00,  3.37847172e+01, -4.42281657e+02],
         ...,
         [ 7.99123235e+00,  6.31073020e+01, -1.32055661e+02],
         [ 6.86363514e-01,  6.88443294e+01, -1.19478931e+02],
         [ 7.84415445e-01,  4.17528109e+01, -1.38344025e+02]],

        [[-1.76186222e+00,  2.69298763e+02, -1.44533959e+00],
         [-1.59245239e+00,  1.02223612e+02, -1.71272741e+02],
         [-2.74443922e+00,  2.33025868e+02, -1.53205996e+02],
         ...,
         [-5.25170469e+0

In [ ]:
# (480,640,3) 인 이미지에 [0.5, 0.5, 1] 을 곱한 이미지 효과는 무엇일까?
f = np.random.randint(2, size=[640,1])

- reshape

In [19]:
a = np.array([1,2,3,4,5])
b = np.array([[1],[2],[3],[4],[5]])

In [20]:
a

array([1, 2, 3, 4, 5])

In [21]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
b.shape

(5, 1)

In [23]:
c = a.reshape(5,1)
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [28]:
a.reshape(5,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])